# Generated by Django 4.1.2 on 2022-11-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('vehicle_vin', models.CharField(max_length=17)),
                ('service_period', models.IntegerField()),
                ('last_service', models.DateField()),
                ('next_service', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('trailer_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('trailer_license', models.CharField(max_length=7)),
                ('trailer_vin', models.CharField(max_length=17)),
                ('trailer_identifier', models.CharField(max_length=15)),
                ('trailer_department', models.IntegerField(blank=True, null=True)),
                ('trailer_short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('trailer_description', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_service_period', models.IntegerField(blank=True, null=True)),
                ('trailer_last_service', models.DateField(blank=True, null=True)),
                ('trailer_next_service', models.DateField(blank=True, null=True)),
                ('trailer_last_dot', models.DateField(blank=True, null=True)),
                ('trailer_next_dot', models.DateField(blank=True, null=True)),
                ('trailer_last_dot_status', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('vehicle_license', models.CharField(max_length=7)),
                ('vehicle_vin', models.CharField(max_length=17)),
                ('vehicle_identifier', models.CharField(max_length=15)),
                ('vehicle_department', models.IntegerField(blank=True, null=True)),
                ('vehicle_short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_description', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_employee', models.CharField(blank=True, max_length=50, null=True)),
                ('service_period', models.IntegerField(blank=True, null=True)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('last_service_miles', models.IntegerField(blank=True, null=True)),
                ('next_service', models.DateField(blank=True, null=True)),
                ('next_service_miles', models.IntegerField(blank=True, null=True)),
                ('last_dot', models.DateField(blank=True, null=True)),
                ('next_dot', models.DateField(blank=True, null=True)),
                ('last_dot_status', models.BooleanField(blank=True, default=True)),
                ('assigned_trailer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(blank=True, null=True)),
                ('service_miles', models.IntegerField(blank=True, null=True)),
                ('service_notes', models.TextField(blank=True, max_length=200, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('repair_miles', models.IntegerField(blank=True, null=True)),
                ('repair_notes', models.TextField(blank=True, max_length=200, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_inspection_date', models.DateField()),
                ('dot_miles', models.IntegerField(blank=True, null=True)),
                ('dot_repair_notes', models.TextField()),
                ('dot_passed_inspection', models.BooleanField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TrailerServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_service_date', models.DateField(blank=True, null=True)),
                ('trailer_service_notes', models.TextField(blank=True, max_length=200, null=True)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='TrailerRepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_repair_date', models.DateField(blank=True, null=True)),
                ('trailer_repair_notes', models.TextField(blank=True, max_length=200, null=True)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='TrailerDotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_dot_inspection_date', models.DateField(blank=True, null=True)),
                ('trailer_dot_repair_notes', models.TextField(blank=True, null=True)),
                ('trailer_dot_passed_inspection', models.BooleanField(blank=True, null=True)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.trailer')),
            ],
        ),
    ]
