# Generated by Django 4.1.2 on 2022-11-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='trailer_last_dot_status',
            field=models.BooleanField(default=True),
        ),
    ]
