# Generated by Django 4.1.2 on 2022-11-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_trailer_trailer_last_dot_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_service',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='next_service',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='service_period',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='vehicle_vin',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_assigned_employee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_assigned_project',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_department',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_identifier',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_last_dot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_last_dot_status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_last_service',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_last_service_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_license',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_next_dot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_next_service',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_next_service_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_service_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_service_date', models.DateField(blank=True, null=True)),
                ('equipment_service_hours', models.IntegerField(blank=True, null=True)),
                ('equipment_service_notes', models.TextField(blank=True, max_length=200, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_repair_date', models.DateField(blank=True, null=True)),
                ('equipment_repair_miles', models.IntegerField(blank=True, null=True)),
                ('equipment_repair_notes', models.TextField(blank=True, max_length=200, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.equipment')),
            ],
        ),
    ]
