# Generated by Django 4.1.2 on 2022-11-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_equipment_id_remove_equipment_last_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_license',
        ),
    ]
