# Generated by Django 4.1.2 on 2022-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_equipment_equipment_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentservicerecord',
            name='equipment_next_service_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
