# Generated by Django 4.1.2 on 2022-11-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_equipmentservicerecord_equipment_next_service_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_license',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_vin',
            field=models.CharField(max_length=20),
        ),
    ]
