# Generated by Django 4.1.2 on 2022-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_vehicle_vehicle_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
