# Generated by Django 4.1.2 on 2022-11-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_vehicle_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='trailer_status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
