# Generated by Django 4.1.2 on 2022-11-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_equipment_equipment_status_trailer_trailer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_last_dot_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Passed'), (False, 'Failed')], default=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='trailerdotrecord',
            name='trailer_dot_passed_inspection',
            field=models.BooleanField(choices=[(True, 'Passed'), (False, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_dot_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Passed'), (False, 'Failed')], default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='vehicledotrecord',
            name='dot_passed_inspection',
            field=models.BooleanField(choices=[(True, 'Passed'), (False, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='vehicledotrecord',
            name='dot_repair_notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
