# Generated by Django 4.1.2 on 2022-11-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_trailerdotrecord_trailer_dot_passed_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_identifier',
            field=models.IntegerField(max_length=4),
        ),
    ]
