# Generated by Django 4.1.2 on 2022-11-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_vehicle_vehicle_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_identifier',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_identifier',
            field=models.IntegerField(),
        ),
    ]
