# Generated by Django 4.1.2 on 2022-11-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_vehicle_vehicle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrepairrecord',
            name='equipment_repair_notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentservicerecord',
            name='equipment_service_notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trailerrepairrecord',
            name='trailer_repair_notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trailerservicerecord',
            name='trailer_service_notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledotrecord',
            name='dot_repair_notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerepairrecord',
            name='repair_notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleservicerecord',
            name='service_notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
