# Generated by Django 4.1.2 on 2022-12-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_equipment_equipment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='weekly_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
