# Generated by Django 4.1.2 on 2022-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_vehicle_weekly_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_weekly_check',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='track_weekly_miles',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
