# Generated by Django 4.1.2 on 2022-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_vehicle_last_weekly_check_vehicle_track_weekly_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='service_period_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
