# Generated by Django 4.1.2 on 2022-12-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_vehicle_service_period_miles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_weekly_check',
            field=models.DateField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='next_service_miles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weekly_miles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
