# Generated by Django 4.1.2 on 2022-12-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_vehicle_last_weekly_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_weekly_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
